### ISSUE TITLE
UserRepo not defined

### ISSUE THREAD

**Issue by Max9545** [rachelbuchta/fitlit-starter-kit#44]
**Describe the bug**

Cannot get both DOM to function and tests to pass at the same time without instantiating or not the classes used

**To Reproduce**
1. Go to UserActivity.js
2. Click on uncomment or re comment all three lines of definitions at top
3. Also check HTML

**Expected behavior**
 **Need both tests to work and html tat same time**

**Comment by rachelbuchta** [comment]
FIXED!!!
